# Name of the workflow as it appears in the Actions tab
name: Hello World

# Specifies when the workflow should run
on:
  # Triggers the workflow on push events to any branch
  push:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Defines a series of jobs to run
jobs:
  # The ID for the job, in this case, 'my-job'
  my-job:
    # Specifies the type of virtual machine to run the job on
    runs-on: ubuntu-latest

    # The steps for the job
    steps:
      # Step 1: Prints a message to the console
      - name: My first step
        run: echo "Hello World from Bratlien!"

      # Step 2: Prints a second message
      - name: My second step
        run: echo "This is my simple GitHub Action."
        
      #step 3: Trigger API JOB
      - name: Trigger API job        
        run: |
          echo "client_id=${{secrets.UIPATH_CLIENT_ID}}"
          echo "client_secret=${{secrets.UIPATH_CLIENT_SECRET}}" 
          echo "Requesting Bearer Token .... " 
          response=$(curl -X POST "https://staging.uipath.com/identity_/connect/token" -H "Content-Type:application/x-www-form-urlencoded" -d "grant_type=client_credentials&client_id=${{secrets.UIPATH_CLIENT_ID}}&client_secret=${{secrets.UIPATH_CLIENT_SECRET}}&scope=TM.Default" )

          echo "Response: $response"
          token=$(echo "$response" | jq -r '.access_token')
          if [ "$token" = "null" ] || [ -z "$token" ]; then
           echo "Failed to get bearer token"
          exit 1
          fi
        


